//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppMVC2017Version
{
    using System;
    using System.Collections.Generic;
    
    public partial class GameInfo
    {
        public string GameName { get; set; }
        public int GameID { get; set; }
        public string GameGenre { get; set; }
    }
}
